name: tungo_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_signin_button: ^2.1.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  http: ^1.5.0
  image_picker: ^1.2.0
  image: ^4.0.17
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_install.png"
#flutter clean
#flutter pub cache repair
#flutter pub get
#flutter pub run flutter_launcher_icons
#flutter build apk

flutter:

  uses-material-design: true

  assets:
    - assets/images/
